### ISSUE TITLE
Not working at all :/

### ISSUE THREAD

**Issue by ascanio** [finchalyzer/slinky#1]
http://recordit.co/q6CPnfDkC1

**Comment by finchalyzer** [comment]
@ascanio Could you please try to make the Artboard you want to export **not** exportable *(select the Artboard and remove the PNG export option from it)* and then try to export the template?

**Comment by finchalyzer** [comment]
Fixed at 35eaf018e8e21740af6e7e5878c42d0e8f11ddfb
