### ISSUE TITLE
Compatibility Issue with Sketch 44

### ISSUE THREAD

**Issue by fbasara-loft48** [finchalyzer/slinky#12]
Since Sketch 44, Slinky does not go past the modal window where one can choose the output destination. No errors were displayed.

**Comment by finchalyzer** [comment]
Looks like Sketch 44 had some minor changesin function names, fixed in 5fcb96b935b25dccf12a0f06cc50f070ffb3f90b

**Comment by fbasara-loft48** [comment]
Thank you very much. I see we have the same test in logo design 👍
