### ISSUE TITLE
Sketch 44 compatibility

### ISSUE THREAD

**Issue by Pro-Paul** [finchalyzer/slinky#13]
Will you update for a Sketch 44 compatibility?

**Comment by finchalyzer** [comment]
@p5uln try the last [0.1.3 release](https://github.com/finchalyzer/slinky/releases/tag/v0.1.3) in which compatibility bugs with Sketch 44 are fixed.

I'll keep this issue open in case something unexpected comes up 😬

**Comment by fbasara-loft48** [comment]
Does Sketchpacks get the update from GitHub or do you update it there manually? If the latter, do you mind pushing 0.13 to Sketchpacks aswell?

**Comment by finchalyzer** [comment]
@fbasara-loft48 Sketchpacks should update automatically and looks like it's caught up the last version - https://sketchpacks.com/finchalyzer/slinky

**Comment by fbasara-loft48** [comment]
@finchalyzer awesome, thank you!

**Comment by Pro-Paul** [comment]
Hello world.
