### ISSUE TITLE
Export is not working

### ISSUE THREAD

**Issue by loaibassam** [finchalyzer/slinky#15]
I've tried to export the document, but nothing gets exported at all. Am I missing something?

**Comment by elliottregan** [comment]
@loaibassam More details would be helpful to anyone looking at this. Share the Sketch file you were working on or something.

**Comment by loaibassam** [comment]
@elliottregan I tried to use one of the templated ones, here: https://github.com/finchalyzer/slinky/blob/master/templates/single-column.sketch

I clicked export, but it does not export it, it seems like it had but i couldn't find any files exported. 

Have you come along this issue before?

**Comment by finchalyzer** [comment]
@loaibassam To investigate further on what could be the problem - please report the following - your Sketch version, are you running the latest version of Slinky ([0.1.3](https://github.com/finchalyzer/slinky/releases/tag/v0.1.3)) and just in case your macOS version.

**Comment by loaibassam** [comment]
Thanks for taking the time to help. 

Sketch is 44.1
Slinky is 0.1.1
Mac is: 10.12.5

**Comment by finchalyzer** [comment]
@loaibassam Update to the latest [Slinky 0.1.3](https://github.com/finchalyzer/slinky/releases/tag/v0.1.3) version and see how it goes.

**Comment by loaibassam** [comment]
Any idea how? I can’t see to be able to find a way.

**Comment by elliottregan** [comment]
Download it again. 

I haven't used Sketchpacks, but the link in this repo's readme makes it look really easy to use.

**Comment by loaibassam** [comment]
Thank you, works now!

**Comment by lsills-jacksonspalding** [comment]
I'm having the same issue but am using Sketch 45, Slinky 0.1.3, and Mac 10.12.5 

@finchalyzer Any idea why it won't export?

**Comment by elliottregan** [comment]
@lsills-jacksonspalding It will be helpful to share the document you are working with. Is it one of the demos?

**Comment by finchalyzer** [comment]
@lsills-jacksonspalding for Sketch 45, please update to [Slinky 0.1.4](https://github.com/finchalyzer/slinky/releases/tag/v0.1.4)

**Comment by ilianateran** [comment]
I am also having this problem as of today. I was able to export just fine on Monday, but now the html file is blank when it exports.

I'm using: Sketch 45.1, Slinky 0.1.4, Mac10.11.6

**Comment by finchalyzer** [comment]
@ilianateran can you please try the export with one of [Slinky provided templates](https://github.com/finchalyzer/slinky/tree/master/templates)? If that works, it's something specific with your Sketch template (it would be really helpful to me to get hands on that privately) if that does not work - can you please provide what other Sketch plugin you have installed?

**Comment by samprimo** [comment]
Same issue! Works with one of the templates, but not much else.

Sketch 45.1, Slinky 0.1.4, Mac OS 10.12.6 Beta

**Comment by samprimo** [comment]
I managed to my my design work. The trick is making sure that everything is sliced (made exportable) before exporting. Once all paths, images and shapes were made exportable, the Slinky exported the design without any faults.

**Comment by moskvin** [comment]
Export images does not work for

* Sketch: 47.1
* Slinky: 0.1.4
* templates/two-columns.sketch

Result:
![two columns html](https://user-images.githubusercontent.com/689561/33356583-ddcf42c6-d4ef-11e7-80e6-13365ebedb82.png)

**Comment by moskvin** [comment]
Seems it relates to [Apple bug](https://forums.developer.apple.com/thread/28336)

**Comment by moskvin** [comment]
Hi!
I've fixed the issue, please check PR #23 and confirm that it works on your side
Thank you

**Comment by finchalyzer** [comment]
Thanks @moskvin for the input 🤘
