### ISSUE TITLE
Slinky wont export

### ISSUE THREAD

**Issue by callummosoph** [finchalyzer/slinky#18]
Hi I am using slinky on sketch, Macbook pro touch bar 13" and when ever i try to export out a simple design as a test (some text on a square) to my desktop its not there and its not backed up on my iCloud either. so i am guessing its just not export anything out of the programme 

i am using the trial and will be purchasing sketch on the 17th Aug but does using it on the trial make it not work. ?

**Comment by finchalyzer** [comment]
Duplicate issue #15
