### ISSUE TITLE
Export to Inky

### ISSUE THREAD

**Issue by rafaelramalho19** [finchalyzer/slinky#4]
Quick suggestion, but this plugin should be able to export to Inky, and if possible follow the Foundation Email guidelines, so we developers can use it as a base template.

**Comment by custa1200** [comment]
I agree, with the name Slinky I was hoping that this would be using Inky (Foundation Emails) under the hood. 

They have spent a lot of time narrowing in on email issues so would have thought it would be better to leverage their work. as the OP says being able to drop it into that workflow would be a massive advantage.

**Comment by finchalyzer** [comment]
Will definitely look into [Inky](https://foundation.zurb.com/emails/docs/inky.html)! My bad that I found out about this framework just after creating the initial plugin.

**Comment by custa1200** [comment]
Don't stress on it. :) will be watching this extension to see how it progresses though.

**Comment by phaedryx** [comment]
Another vote for Inky support
