### ISSUE TITLE
Images not exporting

### ISSUE THREAD

**Issue by zilos** [finchalyzer/slinky#6]
The images for some reason are not exporting. I have them all set up to export but none get exported. 
Any help would be greatly appreciated. 

Thanks for the hard work!

**Comment by finchalyzer** [comment]
@zilos Could you please check these steps:
1. Is your Sketch file saved? Slinky can't export the images if the file is not saved containing those images and should warn you about this.
2. Is there a subfolder `assets` created in the folder where you export the html file? Slinky exports the image assets to that folder.
3. If the folder is there – is it empty?
4. If the folder is not there – could you try to create it manually and then export the template again?
5. If all of above does not work, to investigate further I would love to see the guilty sketch file or at least a screenshot of it. You can reach me privately also at human@finch.io

**Comment by zilos** [comment]
Looks like its working now. I updated Sketch to Version 43 and it now works perfectly.

Thank you!
